In [2]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle

In [3]:
df_legitimate = pd.read_csv('Results/resultfile1.csv',nrows=100000)
df_legitimate.fillna(0, inplace=True)
df_legitimate['target'] = 'legitimate'
print("Shape of Normal Packet: " + str(df_legitimate.shape))

Shape of Normal Packet: (1537, 17)


In [4]:
df_legitimate

second  src  dst  packetcount  src_ratio  dst_ratio  src_duration_ratio  \
0       60.0   38   49           29   0.467742   0.919355            0.711757   
1       60.0   44   49           28   0.451613   0.919355            0.273076   
2       60.0   20    5            5   0.080645   0.080645            0.015167   
3       61.0   32   49           29   0.224806   0.914729            0.216242   
4       61.0   33   49           29   0.224806   0.914729            0.167137   
...      ...  ...  ...          ...        ...        ...                 ...   
1532   862.0   37   49           29   0.878788   0.878788            0.263342   
1533   862.0   31   48            4   0.121212   0.121212            0.736658   
1534   863.0   48   31            5   1.000000   1.000000            1.000000   
1535   866.0   16    5            1   1.000000   1.000000            1.000000   
1536   868.0   22    5            1   1.000000   1.000000            0.000000   

      dst_duration_ratio  TotalPacketDuration  TotalPacketLenght  \
0               0.984833             0.563000               2871   
1               0.984833             0.216003               2772   
2               0.015167             0.011997                445   
3               0.957509             0.229000               2871   
4               0.957509             0.176998               2871   
...                  ...                  ...                ...   
1532            0.263342             0.390015               2871   
1533            0.736658             1.091003                272   
1534            1.000000             0.000977                340   
1535            1.000000             0.078003                 89   
1536            0.000000             0.000000                 89   

      src_packet_ratio  dst_packet_ratio  DioCount  DisCount  DaoCount  \
0             0.471583          0.926905        29         0         0   
1             0.455322          0.926905        28         0         0   
2             0.073095          0.073095         0         0         0   
3             0.226759          0.922676        29         0         0   
4             0.226759          0.922676        29         0         0   
...                ...               ...       ...       ...       ...   
1532          0.913458          0.913458        29         0         0   
1533          0.086542          0.086542         0         0         0   
1534          1.000000          1.000000         0         0         0   
1535          1.000000          1.000000         0         0         0   
1536          1.000000          1.000000         0         0         0   

      OtherMsg      target  
0            0  legitimate  
1            0  legitimate  
2            5  legitimate  
3            0  legitimate  
4            0  legitimate  
...        ...         ...  
1532         0  legitimate  
1533        47  legitimate  
1534        32  legitimate  
1535        50  legitimate  
1536        31  legitimate  

[1537 rows x 17 columns]

In [5]:
df_dis_flood = pd.read_csv('Results/dis_flood.csv')
df_dis_flood.fillna(0, inplace=True)
df_dis_flood['target'] = 'dis_flood'
print("Shape of dis_flood: " + str(df_dis_flood.shape))

Shape of dis_flood: (876, 17)


In [6]:
df_dis_flood

second  src  dst  packetcount  src_ratio  dst_ratio  src_duration_ratio  \
0      60.0    8    4            5   0.833333   0.833333            0.882406   
1      60.0    3    0            1   0.166667   0.166667            0.117594   
2      61.0    3    0            1   0.200000   0.200000            0.083426   
3      61.0    9    4            4   0.800000   0.800000            0.916574   
4      62.0   13    4            1   0.500000   1.000000            0.400458   
..      ...  ...  ...          ...        ...        ...                 ...   
871   752.0   15    4            1   1.000000   1.000000            1.000000   
872   753.0   47   54           29   1.000000   1.000000            1.000000   
873   754.0   23    4            4   0.800000   0.800000            0.059622   
874   754.0    2    0            1   0.200000   0.200000            0.940378   
875   755.0   23    4            1   1.000000   1.000000            0.000000   

     dst_duration_ratio  TotalPacketDuration  TotalPacketLenght  \
0              0.882406             0.014999                392   
1              0.117594             0.001999                106   
2              0.083426             0.002003                106   
3              0.916574             0.022003                303   
4              1.000000             0.002003                 89   
..                  ...                  ...                ...   
871            1.000000             0.067017                 89   
872            1.000000             1.458984               2871   
873            0.059622             0.067017                356   
874            0.940378             1.057007                106   
875            0.000000             0.000000                 36   

     src_packet_ratio  dst_packet_ratio  DioCount  DisCount  DaoCount  \
0            0.787149          0.787149         0         0         0   
1            0.212851          0.212851         0         0         0   
2            0.259169          0.259169         0         0         0   
3            0.740831          0.740831         0         0         0   
4            0.500000          1.000000         0         0         0   
..                ...               ...       ...       ...       ...   
871          1.000000          1.000000         0         0         0   
872          1.000000          1.000000        29         0         0   
873          0.770563          0.770563         0         0         0   
874          0.229437          0.229437         0         0         0   
875          1.000000          1.000000         0         0         0   

     OtherMsg     target  
0           5  dis_flood  
1           1  dis_flood  
2           2  dis_flood  
3           4  dis_flood  
4           1  dis_flood  
..        ...        ...  
871        20  dis_flood  
872         0  dis_flood  
873        63  dis_flood  
874        48  dis_flood  
875        64  dis_flood  

[876 rows x 17 columns]

In [7]:
df_sinkhole = pd.read_csv('Results/sinkhole.csv')
df_sinkhole.fillna(0, inplace=True)
df_sinkhole['target'] = 'sinkhole'
print("Shape of sinkhole: " + str(df_sinkhole.shape))

Shape of sinkhole: (997, 17)


In [8]:
df_sinkhole

second  src  dst  packetcount  src_ratio  dst_ratio  src_duration_ratio  \
0      60.0   54   67           29   0.783784      1.000            0.532479   
1      60.0   52   67            8   0.216216      1.000            0.467521   
2      61.0   17    7            1   0.200000      1.000            0.020823   
3      61.0   22    7            4   0.800000      1.000            0.979177   
4      62.0    1    0            1   0.500000      0.500            0.345788   
..      ...  ...  ...          ...        ...        ...                 ...   
992  3442.0    2    0            1   0.125000      0.125            0.186799   
993  3442.0   33    7            1   0.125000      0.875            0.375578   
994  3442.0   34    7            1   0.125000      0.875            0.137954   
995  3443.0   29    7            4   0.800000      0.800            0.652893   
996  3443.0    5    0            1   0.200000      0.200            0.347107   

     dst_duration_ratio  TotalPacketDuration  TotalPacketLenght  \
0              1.000000             0.582001               2871   
1              1.000000             0.511002                792   
2              1.000000             0.001999                 89   
3              1.000000             0.093998                356   
4              0.345788             0.036999                106   
..                  ...                  ...                ...   
992            0.186799             0.069092                106   
993            0.813201             0.138916                 89   
994            0.813201             0.051025                 89   
995            0.652893             0.077148                303   
996            0.347107             0.041016                106   

     src_packet_ratio  dst_packet_ratio  DioCount  DisCount  DaoCount  \
0            0.783784          1.000000        29         0         0   
1            0.216216          1.000000         8         0         0   
2            0.200000          1.000000         0         0         0   
3            0.800000          1.000000         0         0         0   
4            0.746479          0.746479         0         0         0   
..                ...               ...       ...       ...       ...   
992          0.156805          0.156805         0         0         0   
993          0.131657          0.843195         0         0         0   
994          0.131657          0.843195         0         0         0   
995          0.740831          0.740831         0         0         0   
996          0.259169          0.259169         0         0         0   

     OtherMsg    target  
0           0  sinkhole  
1           0  sinkhole  
2           1  sinkhole  
3           4  sinkhole  
4           1  sinkhole  
..        ...       ...  
992        35  sinkhole  
993        12  sinkhole  
994        17  sinkhole  
995        53  sinkhole  
996        24  sinkhole  

[997 rows x 17 columns]

In [9]:
df_version_number = pd.read_csv('Results/version_number.csv')
df_version_number.fillna(0, inplace=True)
df_version_number['target'] = 'version_num'
print("Shape of sinkhole: " + str(df_version_number.shape))

Shape of sinkhole: (1734, 17)


In [10]:
df_version_number

second  src  dst  packetcount  src_ratio  dst_ratio  src_duration_ratio  \
0       60.0   27   44           12   0.335106   0.675532            0.353415   
1       60.0   22   44           32   0.170213   0.675532            0.233934   
2       60.0   27   40           51   0.335106   0.297872            0.353415   
3       60.0   29   44           11   0.058511   0.675532            0.046182   
4       60.0   42   22            5   0.111702   0.026596            0.094383   
...      ...  ...  ...          ...        ...        ...                 ...   
1729   418.0   28   44           16   1.000000   1.000000            1.000000   
1730   419.0   28   44           13   1.000000   1.000000            1.000000   
1731   420.0   28   44           27   0.843750   0.843750            0.998275   
1732   420.0   27   23            5   0.156250   0.156250            0.001725   
1733   421.0   28   44            5   1.000000   1.000000            1.000000   

      dst_duration_ratio  TotalPacketDuration  TotalPacketLenght  \
0               0.690760             0.067001               1188   
1               0.690760             0.232998               3168   
2               0.308233             0.285000               3978   
3               0.690760             0.045998               1089   
4               0.001007             0.001003                390   
...                  ...                  ...                ...   
1729            1.000000             0.169006               1056   
1730            1.000000             1.277008                858   
1731            0.998275             1.148010               1782   
1732            0.001725             0.001984                390   
1733            1.000000             0.002991                330   

      src_packet_ratio  dst_packet_ratio  DioCount  DisCount  DaoCount  \
0             0.312977          0.711741        12         0         0   
1             0.191930          0.711741        32         0         0   
2             0.312977          0.264631         0         0        51   
3             0.065976          0.711741        11         0         0   
4             0.119593          0.023628         0         0         5   
...                ...               ...       ...       ...       ...   
1729          1.000000          1.000000         0        16         0   
1730          1.000000          1.000000         0        13         0   
1731          0.820442          0.820442         0        27         0   
1732          0.179558          0.179558         0         0         5   
1733          1.000000          1.000000         0         5         0   

      OtherMsg       target  
0            0  version_num  
1            0  version_num  
2            0  version_num  
3            0  version_num  
4            0  version_num  
...        ...          ...  
1729     16209  version_num  
1730     16222  version_num  
1731     16249  version_num  
1732         0  version_num  
1733     16254  version_num  

[1734 rows x 17 columns]

In [11]:
print("Starting concatenate dataset")
df = pd.concat([df_legitimate,df_dis_flood,df_sinkhole,df_version_number], ignore_index=True)
df = shuffle(df,random_state=10)


Starting concatenate dataset


In [12]:
df.to_csv (r'./attack_all.csv', index = False, header=True)


In [13]:
df

second  src  dst  packetcount  src_ratio  dst_ratio  src_duration_ratio  \
4884   332.0   25   42           10   0.116279   0.116279            0.009576   
960    560.0    6    5            1   0.142857   0.857143            0.073593   
2889   398.0   32    7            1   0.333333   1.000000            0.307064   
4855   325.0   28   44           59   0.556604   0.556604            0.229542   
3156  3283.0   63   58            4   0.200000   0.200000            0.076956   
...      ...  ...  ...          ...        ...        ...                 ...   
1180   677.0   19    5            1   0.047619   0.285714            0.044715   
3441    63.0   26   44            5   0.056180   0.842697            0.047152   
1344   774.0   34   29            4   0.800000   0.800000            0.896970   
4623   277.0   37   35            5   0.037037   0.037037            0.109851   
1289   746.0   22    5            1   0.500000   1.000000            0.500000   

      dst_duration_ratio  TotalPacketDuration  TotalPacketLenght  \
4884            0.009576             0.007019                780   
960             0.857143             0.001038                 89   
2889            1.000000             0.039001                 89   
4855            0.229542             0.227020               3894   
3156            0.076956             0.044189                272   
...                  ...                  ...                ...   
1180            0.288618             0.002014                 89   
3441            0.712182             0.048000                495   
1344            0.896970             0.009033                272   
4623            0.109851             0.106995                390   
1289            1.000000             0.001953                 89   

      src_packet_ratio  dst_packet_ratio  DioCount  DisCount  DaoCount  \
4884          0.129741          0.129741         0         0        10   
960           0.151618          0.819421         0         0         0   
2889          0.333333          1.000000         0         0         0   
4855          0.515079          0.515079         0        59         0   
3156          0.196959          0.196959         0         0         0   
...                ...               ...       ...       ...       ...   
1180          0.057830          0.312541         0         0         0   
3441          0.072084          0.840979         5         0         0   
1344          0.753463          0.753463         0         0         0   
4623          0.040273          0.040273         0         0         5   
1289          0.500000          1.000000         0         0         0   

      OtherMsg       target  
4884         0  version_num  
960         20   legitimate  
2889         6     sinkhole  
4855     13424  version_num  
3156         4     sinkhole  
...        ...          ...  
1180        23   legitimate  
3441         0  version_num  
1344        31   legitimate  
4623         0  version_num  
1289        27   legitimate  

[5144 rows x 17 columns]

In [14]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.layers import Convolution1D, LSTM
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import plot_confusion_matrix
from warnings import simplefilter
import time
start = time.time()


In [15]:
df = pd.read_csv("attack_all.csv") 
seed = 7
class_names = df.target.unique()
df=df.astype('category')
cat_columns = df.select_dtypes(['category']).columns
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)
y = df['target']
x_columns = df.columns.drop('target')
x = df[x_columns].values


print("Ready to generate train and test datasets")
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=seed)
print("x_train, y_train, x_test, y_test" + str(x_train.shape) + "" +str(y_train.shape) + "" +str(x_test.shape) + "" +str(y_test.shape))

Ready to generate train and test datasets
x_train, y_train, x_test, y_test(3600, 16)(3600,)(1544, 16)(1544,)


In [16]:
list_of_column_names = list(df.columns)
 
print('List of the features: \n')
for i in list_of_column_names:
  print(i)

List of the features: 

second
src
dst
packetcount
src_ratio
dst_ratio
src_duration_ratio
dst_duration_ratio
TotalPacketDuration
TotalPacketLenght
src_packet_ratio
dst_packet_ratio
DioCount
DisCount
DaoCount
OtherMsg
target


In [17]:
print(class_names)

['version_num' 'legitimate' 'sinkhole' 'dis_flood']


In [18]:
len(df)

5144

In [19]:
print("Ready to generate train and test datasets")

#Neural network
model = Sequential()
model.add(Dense(50, input_dim=x_train.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(30, input_dim=x_train.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(20, kernel_initializer='normal'))
model.add(Dense(4,activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto')
history = model.fit(x_train,y_train,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=200,batch_size=1000) 
end = time.time()
diff=end-start
print("Training time: " + str(diff))
starttest = time.time()
y_pred_nn = model.predict(x_test)
y_pred_nn = np.argmax(y_pred_nn,axis=1)
endtest =time.time()
difftest = endtest-starttest
print("Test time: " + str(difftest))

print(model.summary())


Ready to generate train and test datasets
Epoch 1/200
4/4 - 2s - loss: 7.1175 - accuracy: 0.2983 - val_loss: 3.0889 - val_accuracy: 0.3206 - 2s/epoch - 577ms/step
Epoch 2/200
4/4 - 0s - loss: 3.2256 - accuracy: 0.3153 - val_loss: 2.8040 - val_accuracy: 0.2636 - 95ms/epoch - 24ms/step
Epoch 3/200
4/4 - 0s - loss: 2.0749 - accuracy: 0.3444 - val_loss: 1.6014 - val_accuracy: 0.5194 - 102ms/epoch - 26ms/step
Epoch 4/200
4/4 - 0s - loss: 1.7779 - accuracy: 0.4703 - val_loss: 1.3719 - val_accuracy: 0.5175 - 67ms/epoch - 17ms/step
Epoch 5/200
4/4 - 0s - loss: 1.3541 - accuracy: 0.4461 - val_loss: 1.2612 - val_accuracy: 0.4462 - 62ms/epoch - 15ms/step
Epoch 6/200
4/4 - 0s - loss: 1.2366 - accuracy: 0.4864 - val_loss: 1.1058 - val_accuracy: 0.5538 - 64ms/epoch - 16ms/step
Epoch 7/200
4/4 - 0s - loss: 1.1521 - accuracy: 0.5433 - val_loss: 1.1085 - val_accuracy: 0.5622 - 64ms/epoch - 16ms/step
Epoch 8/200
4/4 - 0s - loss: 1.0606 - accuracy: 0.5867 - val_loss: 1.0070 - val_accuracy: 0.6004 - 87ms/

In [20]:
print("Neural network, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_nn)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_nn,average='weighted')))
matrixnn = confusion_matrix(y_test,y_pred_nn)
print(matrixnn)

Neural network, accuracy: 0.7707253886010362 F1 score:0.7721443587432433
[[103  40  79  20]
 [ 43 361  18  10]
 [ 93   4 204  14]
 [ 18   8   7 522]]


In [21]:
x_test

array([[201,   0,   0, ...,   0,   0,  36],
       [161,  33,  12, ...,   0,   7,   0],
       [413,  32,  23, ...,   0,   0,  12],
       ...,
       [ 40,  62,  48, ...,   0,   0,   0],
       [215,  24,  25, ...,   0,   0,   0],
       [ 27,  42,  30, ...,   0,   0,   0]], dtype=int16)

In [22]:
for i in y_pred_nn:
  print(class_names[i])

legitimate
dis_flood
version_num
legitimate
legitimate
legitimate
version_num
dis_flood
legitimate
dis_flood
version_num
legitimate
legitimate
legitimate
version_num
legitimate
dis_flood
version_num
dis_flood
dis_flood
sinkhole
dis_flood
dis_flood
dis_flood
dis_flood
dis_flood
dis_flood
dis_flood
sinkhole
version_num
legitimate
legitimate
sinkhole
legitimate
dis_flood
dis_flood
dis_flood
legitimate
legitimate
dis_flood
dis_flood
legitimate
version_num
dis_flood
dis_flood
legitimate
dis_flood
version_num
dis_flood
dis_flood
dis_flood
version_num
version_num
dis_flood
version_num
dis_flood
dis_flood
version_num
legitimate
dis_flood
dis_flood
legitimate
sinkhole
sinkhole
version_num
dis_flood
dis_flood
dis_flood
sinkhole
legitimate
sinkhole
version_num
dis_flood
dis_flood
legitimate
sinkhole
version_num
version_num
dis_flood
legitimate
dis_flood
legitimate
dis_flood
dis_flood
legitimate
legitimate
legitimate
legitimate
dis_flood
dis_flood
sinkhole
legitimate
sinkhole
dis_flood
sinkhole
ve

version_num
legitimate
sinkhole
dis_flood
legitimate
legitimate
legitimate
legitimate
sinkhole
dis_flood
version_num
dis_flood
legitimate
dis_flood
legitimate
dis_flood
dis_flood
sinkhole
sinkhole
dis_flood
legitimate
dis_flood
version_num
dis_flood
dis_flood
dis_flood
legitimate
sinkhole
sinkhole
version_num
dis_flood
dis_flood
legitimate
legitimate
sinkhole
sinkhole
legitimate
legitimate
legitimate
version_num
legitimate
dis_flood
dis_flood
version_num
version_num
dis_flood
legitimate
version_num
legitimate
dis_flood
version_num
version_num
dis_flood
dis_flood
dis_flood
dis_flood
sinkhole
version_num
dis_flood
sinkhole
legitimate
legitimate
sinkhole
dis_flood
sinkhole
version_num
legitimate
legitimate
dis_flood
dis_flood
legitimate
sinkhole
version_num
sinkhole
sinkhole
sinkhole
sinkhole
dis_flood
legitimate
legitimate
legitimate
sinkhole
dis_flood
sinkhole
legitimate
dis_flood
dis_flood
dis_flood
legitimate
sinkhole
dis_flood
version_num
dis_flood
legitimate
legitimate
version_num
d

In [23]:
print("Ready to generate new train and test datasets")
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=seed)
print("x_train, y_train, x_test, y_test" + str(x_train.shape) + "" +str(y_train.shape) + "" +str(x_test.shape) + "" +str(y_test.shape))

y_pred_n = model.predict(x_test)
y_pred_n = np.argmax(y_pred_n,axis=1)


Ready to generate new train and test datasets
x_train, y_train, x_test, y_test(3086, 16)(3086,)(2058, 16)(2058,)
65/65 [==============================] - 0s 3ms/step


In [24]:
print("Neural network, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_n)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_n,average='weighted')))
matrixn = confusion_matrix(y_test,y_pred_n)
print(matrixn)

Neural network, accuracy: 0.7755102040816326 F1 score:0.7759850606900252
[[140  54 100  32]
 [ 60 498  22  14]
 [120   5 269  17]
 [ 20  10   8 689]]


In [25]:
print("Ready to generate new train and test datasets")
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=seed)
print("x_train, y_train, x_test, y_test" + str(x_train.shape) + "" +str(y_train.shape) + "" +str(x_test.shape) + "" +str(y_test.shape))

y_pred = model.predict(x_test)
y_pred = np.argmax(y_pred,axis=1)

Ready to generate new train and test datasets
x_train, y_train, x_test, y_test(4115, 16)(4115,)(1029, 16)(1029,)
33/33 [==============================] - 1s 1ms/step


In [26]:
print("Neural network, accuracy: " + str(metrics.accuracy_score(y_test, y_pred)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred,average='weighted')))
matrixn = confusion_matrix(y_test,y_pred)
print(matrixn)

Neural network, accuracy: 0.783284742468416 F1 score:0.784633199438299
[[ 68  31  47  11]
 [ 26 242  12   4]
 [ 60   4 135   7]
 [ 13   4   4 361]]
